dist: trusty
language: cpp
services:
  - docker
matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - ARCH=amd64
    - os: osx
      osx_image: xcode9
      env:
        - ARCH=i386
    - os: linux
      env:
        - ARCH=amd64
    - os: linux
      env:
        - ARCH=i386
    - os: linux
      env:
        - ARCH=arm
    - os: linux
      env:
        - ARCH=arm64
    - os: linux
      env:
        - ARCH=mips
    - os: linux
      env:
        - ARCH=mips64
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      rvm install ruby-2.4.0;
      rvm --default use 2.4.0;
      ruby -v;
      brew update;
    fi
install:
  - git submodule init
  - git submodule update
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull fibjs/build-env:latest;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install xz;
    fi
script:
  - echo "${ARCH}"
  - ./.travis/build.sh
  - ./.travis/test.sh
  - if [[ "$TRAVIS_TAG" != "" ]]; then 
      ./.travis/release.sh; 
    fi
deploy:
  - provider: releases
    api_key:
      secure: KcAukDuM2vwkr9TJQE8mY5n+dnO7Kp0dd5m634amhcZ+Nfhn8ceJ4DBWqlPXXS6R00OHCTVx5ASega6dcdXJilaFmddtZnjHUV7KDcUt7wj8BSPM91xENi/6CMG1qqS8K1t4lOlGh7zc4ozjF5JB92PscZE7VXvZqH0ki669tu7zZFaKopF/RZez4j+aNx+Bh+dNJKtwNoUw6u4jIlXDxMfO0EFpcOBztBWBSRAF6CM53dBNCFsDK9fyX+0jFzI5ueo+YviBvSUHfQBFOGan0XCSyFY1avBQ4EXbypBQ1yENBviVpIBZmfskdrz+Ei52GuFOGdNCcT2ronJzNp789bBwfg/ZOJ4OuX53LbdybMfdMUQvB2ZSObwVRKi8gju1KxYcgIKS7UKMIluK+77DlOS0REBOmIwsPnMQv2PI2YAEzKoQuCbocfDKMzZlSQlszpjE278tBGmfX1aG06vJNoJdGlm2VunkkAXcp6nYA0PgXkrTRwJUg5r0JnOtSIHpSXsamoZxZoWjFaOZMVrTkEVsDuK6UohsCT2CDW9/Z0m7LeIPSSxXX44BX5LIE+NbcaEGOBmE+fKtWsFSbNjxqW0C/Ag6ukhtOWdzvyrM+dY0uTM9X4jAoJsDzXMOp63jI9P5U02UUO2mnCO+/68Dz9KxqY/O7DfEKZFvOW49PmA=
    file_glob: true
    file: ${TRAVIS_TAG}/*
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      repo: richardo2016/fibjs
